services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_TABLE_PREFIX: ${DB_PREFIX}
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USERNAME}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      # WORDPRESS_CONFIG_EXTRA: |
      #   define('MULTISITE', true);
      #   define('SUBDOMAIN_INSTALL', false);
      #   define('DOMAIN_CURRENT_SITE', 'localhost');
      #   define('PATH_CURRENT_SITE', '/');
      #   define('SITE_ID_CURRENT_SITE', 1);
      #   define('BLOG_ID_CURRENT_SITE', 1);
    depends_on:
      - db
    restart: always
    ports:
      - 8080:80

  db:
    image: mysql:8.0.42
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    restart: always
    ports:
      - 3306:3306

volumes:
  wordpress_data:
  db_data:
